routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'guest'], function () {
    Route::get('/register', 'AuthController@registerForm')->name('register');
    Route::post('/register', 'AuthController@register');
    Route::get('/login', 'AuthController@loginForm')->name('login');
    Route::post('/login', 'AuthController@login');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/logout', 'AuthController@logout')->name('logout');
});

Route::group(
    [
        'namespace'  => 'Cabinet',
        'middleware' => ['auth']
    ],
    function () {
        Route::group(['as' => 'user.'], function () {
            Route::get('/profile/{id}', 'UserController@profile')->name('profile');
            Route::get('/id/{id}', 'UserController@show')->name('show');
            Route::get('/search', 'UserController@search')->name('search');
        });

        Route::group(['prefix' => 'friend', 'as' => 'friend.'], function () {
            Route::get('/list/{id}', 'FriendshipController@showFriends')->name('list');
            Route::post('/add', 'FriendshipController@add')->name('add');
            Route::post('/confirm', 'FriendshipController@confirm')->name('confirm');
            Route::delete('/delete', 'FriendshipController@delete')->name('delete');
        });
    }
);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Cabinet/UserController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Http\Controllers\Controller;
use App\Repositories\FriendshipRepository;
use App\Repositories\UserRepository;
use App\Services\FriendshipService;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * @var FriendshipRepository
     */
    private $friendshipRepository;

    /**
     * @var FriendshipService
     */
    private $friendshipService;

    /**
     * ProfileController constructor.
     * @param UserRepository $userRepository
     * @param FriendshipRepository $friendshipRepository
     * @param FriendshipService $friendshipService
     */
    public function __construct(
        UserRepository $userRepository,
        FriendshipRepository $friendshipRepository,
        FriendshipService $friendshipService
    ) {
        $this->userRepository       = $userRepository;
        $this->friendshipRepository = $friendshipRepository;
        $this->friendshipService    = $friendshipService;
    }

    /**
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function profile(int $id)
    {
        if (auth()->id() !== $id) {
            abort(404);
        }

        try {
            $user = $this->userRepository->getOneById($id);

            if (empty($user)) {
                abort(404);
            }

            list($requestsFromMe, $requestsForMe) = $this->friendshipService->getRequests();
        } catch (\Exception $e) {
            abort(404);
        }

        return view('user.profile', compact('user', 'requestsFromMe', 'requestsForMe'));
    }

    /**
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function show(int $id)
    {
        if ($id === auth()->id()) {
            return redirect()->back();
        }

        try {
            $user = $this->userRepository->getOneById($id);

            if (empty($user)) {
                abort(404);
            }

            $friendship = $this->friendshipRepository->findRequest($id);
        } catch (\Exception $e) {
            abort(404);
        }

        return view('user.show', compact('user', 'friendship'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request)
    {
        $page     = $request->input('page') ?: 1;
        $fullName = trim($request->get('fullName'));
        $names    = explode(' ', $fullName);
        $path     = sprintf('%s?%s', $request->url(), http_build_query($request->except(['page'])));

        if (empty($fullName)) {
            $paginator = $this->userRepository->getAllWithLimit();
        } else {
            $firstName = $names[0] ?? '';
            $lastName  = $names[1] ?? '';
            $paginator = $this->userRepository->findByNames($firstName, $lastName, $page);
        }

        $paginator = $paginator->withPath($path);

        return view('user.search', compact('paginator', 'fullName'));
    }
}

resources/views/user/profile.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @if(session('status'))
                    <div class="alert alert-info">
                        {{ session('status') }}
                    </div>
                @endif

                <div class="card">
                    <div class="card-header">{{ __('Profile') }}</div>

                    <div class="card-body">
                        <table class="table table-bordered table-striped mb-4">
                            <thead>
                            <tr>
                                <th style="width: 150px;">Names</th>
                                <th>Description</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if ($user)
                                @foreach($user->getProfileData() as $key => $value)
                                    <tr style="word-break: break-all;">
                                        <td>{{ $key }}</td>
                                        <td>{{ $value }}</td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>

                        <div class="card mb-4">
                            <div class="card-body">
                                <h5 class="card-title">Friends</h5>
                                <p class="card-text">You can see friends by clicking on the button.</p>
                                <a href="{{ route('friend.list', ['id' => $user->getId()]) }}" class="btn btn-info">View friends</a>
                            </div>
                        </div>

                        <div class="card bg-light mb-4">
                            <div class="card-body">
                                <h5 class="card-title">Friends request from me</h5>
                                <div class="card-columns">
                                    @if ($requestsFromMe)
                                        @foreach($requestsFromMe as $friend)
                                            <div class="card">
                                                <img class="card-img-top" data-src="holder.js/100px180/" alt="100%x180"
                                                     src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22244%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20244%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1718a472f56%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A12pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1718a472f56%22%3E%3Crect%20width%3D%22244%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2291.3046875%22%20y%3D%2295.55%22%3E244x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                                                     data-holder-rendered="true"
                                                     style="height: 180px; width: 100%; display: block;">
                                                <div class="card-body">
                                                    <h5 class="card-title"><a href="{{ route('user.show', ['id' => $friend->getId()]) }}">{{ $friend->getFullName() }}</a></h5>
                                                    <p class="card-text">{{ $friend->getInterests() }}</p>
                                                </div>
                                                <div class="card-footer">
                                                    {{ Form::open(['route' => 'friend.delete', 'method' => 'DELETE']) }}
                                                    {{ Form::hidden('userId', $friend->getId()) }}
                                                    {{ Form::submit('Cancel request', ['class' => 'btn btn-secondary']) }}
                                                    {{ Form::close() }}
                                                </div>
                                            </div>
                                        @endforeach
                                    @else
                                        <p>List empty</p>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="card text-white bg-dark mb-4">
                            <div class="card-body">
                                <h5 class="card-title">Friends request for me</h5>
                                <div class="card-columns">
                                    @if ($requestsForMe)
                                        @foreach($requestsForMe as $friend)
                                            <div class="card text-black-50">
                                                <img class="card-img-top" data-src="holder.js/100px180/" alt="100%x180"
                                                     src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22244%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20244%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1718a472f56%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A12pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1718a472f56%22%3E%3Crect%20width%3D%22244%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2291.3046875%22%20y%3D%2295.55%22%3E244x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                                                     data-holder-rendered="true"
                                                     style="height: 180px; width: 100%; display: block;">
                                                <div class="card-body">
                                                    <h5 class="card-title"><a href="{{ route('user.show', ['id' => $friend->getId()]) }}">{{ $friend->getFullName() }}</a></h5>
                                                    <p class="card-text">{{ $friend->getInterests() }}</p>
                                                </div>
                                                <div class="card-footer row">
                                                    {{ Form::open(['route' => 'friend.delete', 'method' => 'DELETE']) }}
                                                    {{ Form::hidden('userId', $friend->getId()) }}
                                                    {{ Form::submit('Delete', ['class' => 'btn btn-danger col-md-12']) }}
                                                    {{ Form::close() }}

                                                    {{ Form::open(['route' => 'friend.confirm', 'method' => 'POST', 'class' => 'ml-3']) }}
                                                    {{ Form::hidden('userId', $friend->getId()) }}
                                                    {{ Form::submit('Accept', ['class' => 'btn btn-success col-md-12']) }}
                                                    {{ Form::close() }}
                                                </div>
                                            </div>
                                        @endforeach
                                    @else
                                        <p>List empty</p>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/search.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Search') }}</div>

                    <div class="card-body">
                        <form method="GET" action="{{ route('user.search') }}">
                            <div class="form-group row">
                                <label for="fullName" class="col-md-2 col-form-label">{{ __('Full name') }}</label>

                                <div class="col-md-8">
                                    <input id="fullName" type="text" class="form-control" name="fullName" value="{{ $fullName }}" required autocomplete="fullName" autofocus>
                                </div>
                                <div class="col-md-2">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Find') }}
                                    </button>
                                    <a href="{{ route('user.search') }}" class="btn btn-success">Clear</a>
                                </div>
                            </div>
                        </form>

                        @if(!empty($paginator) && $users = $paginator->items())
                            @foreach($users as $user)
                                <div class="card mb-4">
                                    <div class="row no-gutters">
                                        <div class="col-md-2">
                                            <svg class="bd-placeholder-img" width="100%" height="150" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image">
                                                <title>Placeholder</title>
                                                <rect width="100%" height="100%" fill="#868e96"></rect>
                                                <text x="40%" y="50%" fill="#dee2e6" dy=".3em">Image</text>
                                            </svg>
                                        </div>
                                        <div class="col-md-10">
                                            <div class="card-body">
                                                <h5 class="card-title"><a href="{{ route('user.show', ['id' => $user->id]) }}"><b>{{ $user->name . ' ' . $user->surname }}</b></a></h5>
                                                <p class="card-text">{{ $user->city }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach

                            {{ $paginator->links() }}
                        @else
                            <div class="row">
                                <div class="card-body text-center col-mb-12">
                                    <h5 class="card-title">Not found</h5>
                                    <p class="card-text">Sorry, could not find a user with this full name.</p>
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h4>{{ $user->getFullName() }}</h4></div>

                    <div class="card-body">
                        @if(session('status'))
                            <div class="alert alert-info">
                                {{ session('status') }}
                            </div>
                        @endif
                        <table class="table table-bordered table-striped mb-4">
                            <thead>
                            <tr>
                                <th style="width: 150px;">Names</th>
                                <th>Description</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if ($user)
                                @foreach($user->getUserData() as $key => $value)
                                    <tr style="word-break: break-all;">
                                        <td>{{ $key }}</td>
                                        <td>{{ $value }}</td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>

                        <div class="card mb-4">
                            <div class="card-body">
                                <h5 class="card-title">Friends</h5>
                                <p class="card-text">You can see friends by clicking on the button.</p>
                                <a href="{{ route('friend.list', ['id' => $user->getId()]) }}" class="btn btn-info">View friends</a>
                            </div>
                        </div>

                        @if ($user->getId() !== auth()->id())
                            @if (!$friendship)
                                {{ Form::open(['route' => 'friend.add', 'method' => 'POST']) }}
                                {{ Form::hidden('userId', $user->getId()) }}
                                {{ Form::submit('Add as friend', ['class' => 'btn btn-primary']) }}
                                {{ Form::close() }}
                            @else
                                @if ($friendship->isFriend())
                                    <div class="card">
                                        <div class="card-header">Your friend</div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                {{ Form::open(['route' => 'friend.delete', 'method' => 'DELETE']) }}
                                                {{ Form::hidden('userId', $user->getId()) }}
                                                {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                                                {{ Form::close() }}
                                            </li>
                                        </ul>
                                    </div>
                                @else
                                    @if ($friendship->isRequestAsFriendFromMe())
                                        <div class="card">
                                            <div class="card-header">Friend request sent from me</div>
                                            <ul class="list-group list-group-flush">
                                                <li class="list-group-item">
                                                    {{ Form::open(['route' => 'friend.delete', 'method' => 'DELETE']) }}
                                                    {{ Form::hidden('userId', $user->getId()) }}
                                                    {{ Form::submit('Cancel request', ['class' => 'btn btn-secondary']) }}
                                                    {{ Form::close() }}
                                                </li>
                                            </ul>
                                        </div>
                                    @else
                                        <div class="card">
                                            <div class="card-header">Friend request sent for me</div>
                                            <ul class="list-group list-group-flush">
                                                <li class="list-group-item card-columns">
                                                    {{ Form::open(['route' => 'friend.delete', 'method' => 'DELETE',]) }}
                                                    {{ Form::hidden('userId', $user->getId()) }}
                                                    {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                                                    {{ Form::close() }}

                                                    {{ Form::open(['route' => 'friend.confirm', 'method' => 'POST',]) }}
                                                    {{ Form::hidden('userId', $user->getId()) }}
                                                    {{ Form::submit('Accept', ['class' => 'btn btn-success']) }}
                                                    {{ Form::close() }}
                                                </li>
                                            </ul>
                                        </div>
                                    @endif
                                @endif
                            @endif
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection